### ISSUE TITLE
Some variable is named incorrectly.

### ISSUE THREAD

**Issue by SiestaMadokaist** [nandawperdana/android-mvp-architecture#1]
In this file for example: https://github.com/nandawperdana/android-mvp-architecture/blob/master/app/src/main/java/com/nandawperdana/poetryandroidmvp/api/APICallManager.java

Some **static** variable start with prefix m<actualVariableName>, it doesn't conform with android field naming convention (http://source.android.com/source/code-style.html#follow-field-naming-conventions)

> Follow Field Naming Conventions 
> - Non-public, non-static field names start with m.
> - Static field names start with s.
> - Other fields start with a lower case letter.
> - Public static final fields (constants) are ALL_CAPS_WITH_UNDERSCORES.

Or, it's also possible to change it to conform with [google java coding standard](https://google.github.io/styleguide/javaguide.html#s5.1-identifier-names) by completely discarding the hungarian notation.

**Comment by MivoRecruitment** [comment]
wee... mantep.
gw udah lupa dulu kayak gimana.

edit: fuck, salah account.
